# TypeProf 0.30.1

# carro.rb
class Carro
  def marca: -> String
  def modelo: -> String
  def tanque: -> Integer
  def cor: -> String
  def cor=: (untyped) -> String
  def initialize: (String, String, String, Integer) -> Integer
end
