# Classes
class Carro
  attr_reader marca: String
  attr_reader modelo: String
  attr_reader tanque: Integer
  attr_accessor cor: String
  def initialize: (String marca, String modelo, String cor, Integer tanque) -> Integer
end
