# TypeProf 0.30.1

# carro.rb
class Carro
  def marca: -> untyped
  def modelo: -> untyped
  def tanque: -> untyped
  def cor: -> untyped
  def cor=: (untyped) -> untyped
  def initialize: (untyped, untyped, untyped, untyped) -> untyped
end
